library(rpart)
library(rpart.plot)
library(caTools)
stevens <- read.csv("stevens.csv")
set.seed(3000)
split <- sample.split(stevens$Reverse, SplitRatio=.7)
Test <- subset(stevens, split==FALSE)
Train <- subset(stevens, split==TRUE)

StevensTree <- rpart(Reverse~ Circuit+Issue+Petitioner+Respondent+LowerCourt+Unconst, data=Train, method="class", control=rpart.control(minbucket=25))
prp(StevensTree)
PredictCART <- predict(StevensTree, newdata=Test, type="class")
table(Test$Reverse, PredictCART)
library(ROCR)
PredictROC <- predict(StevensTree, newdata=Test)
pred <- prediction(PredictROC[,2], Test$Reverse)
perf <- performance(pred, "tpr", "fpr")
plot(perf)
